export const USERINFOR = [
  {
    staffId: 1,
    userId: 1,
    lastName: "Nguyen",
    firstName: "Ngoc",
    dob: "2003-09-15",
    phone: "0909090909",
    gender: 0,
    address: "hok bik",
    country: "VietNam",
    citizenId: "086728991835",
    departmentId: 1,
    hireDate: "2020-01-01",
    bankAccount: "oidwofew",
    bankAccountName: "Nguyen Bao Ngoc",
    bank: "abbank",
    workTimeByYear: 12,
    isManager: 0,
    accountStatus: 1,
  },
  {
    staffId: 2,
    userId: 2,
    lastName: "Nguyen",
    firstName: "Ngoc",
    dob: "2003-09-15",
    phone: "0909090909",
    gender: 0,
    address: "hok bik",
    country: "VietNam",
    citizenId: "086728991835",
    departmentId: 1,
    hireDate: "2020-01-01",
    bankAccount: "oidwofew",
    bankAccountName: "Nguyen Bao Ngoc",
    bank: "abbank",
    workTimeByYear: 12,
    isManager: 0,
    accountStatus: 1,
  },
  {
    staffId: 3,
    userId: 3,
    lastName: "Nguyen",
    firstName: "Ngoc",
    dob: "2003-09-15",
    phone: "0909090909",
    gender: 0,
    address: "hok bik",
    country: "VietNam",
    citizenId: "086728991835",
    departmentId: 1,
    hireDate: "2020-01-01",
    bankAccount: "oidwofew",
    bankAccountName: "Nguyen Bao Ngoc",
    bank: "abbank",
    workTimeByYear: 12,
    isManager: 0,
    accountStatus: 1,
  },
  {
    staffId: 4,
    userId: 4,
    lastName: "Mai",
    firstName: "Viet",
    dob: "2003-09-15",
    phone: "0909090909",
    gender: 0,
    address: "hok bik",
    country: "VietNam",
    citizenId: "086728991835",
    departmentId: 2,
    hireDate: "2020-01-01",
    bankAccount: "oidwofew",
    bankAccountName: "Nguyen Bao Ngoc",
    bank: "abbank",
    workTimeByYear: 12,
    isManager: 1,
    accountStatus: 1,
  },
  {
    staffId: 5,
    userId: 5,
    lastName: "Nguyen",
    firstName: "Ngoc",
    dob: "2003-09-15",
    phone: "0909090909",
    gender: 0,
    address: "hok bik",
    country: "VietNam",
    citizenId: "086728991835",
    departmentId: 2,
    hireDate: "2020-01-01",
    bankAccount: "oidwofew",
    bankAccountName: "Nguyen Bao Ngoc",
    bank: "abbank",
    workTimeByYear: 12,
    isManager: 0,
    accountStatus: 1,
  },
];

export const DEPARTMENT = [
  { departmentId: 1, departmentName: "Department01" },
  { departmentId: 2, departmentName: "Department02" },
  { departmentId: 3, departmentName: "Department03" },
  { departmentId: 4, departmentName: "Department04" },
  { departmentId: 5, departmentName: "Department05" },
];

export const OTTYPE = [
  { otTypeId: 1, typeName: "Làm thêm ngày trong tuần", typePercentage: 1.5 },
  { otTypeId: 2, typeName: "Làm thêm ngày cuối tuần", typePercentage: 2 },
  { otTypeId: 3, typeName: "Làm thêm ngày lễ", typePercentage: 3 },
];

export const STAFF = {
  staffId: 1,
  userId: 1,
  lastName: "Nguyen",
  firstName: "Ngoc",
  dob: "2003-09-15",
  phone: "0909090909",
  gender: 0,
  address: "hok bik",
  country: "VietNam",
  citizenId: "086728991835",
  departmentId: 1,
  hireDate: "2020-01-01",
  bankAccount: "oidwofew",
  bankAccountName: "Nguyen Bao Ngoc",
  bank: "abbank",
  workTimeByYear: 12,
  isManager: 0,
  accountStatus: 1,
};
export const OTLOG = {
  otLogId: 1,
  staffId: 11,
  otTypeId: 1,
  logStart: "2020-11-11",
  logEnd: "2020-11-11",
  logHours: 3,
  reason: "none",
  status: "Chờ duyệt",
  processNote: "poiuytresdfghjkllkjbv",
  respondenceId: 0,
  createAt: "2020-11-11",
  changeStatusTime: "",
  enable: true,
};

export const OTLOGS = [
  {
    otLogId: 1,
    staffId: 11,
    otTypeId: 1,
    logStart: "2020-11-11 17:00:00",
    logEnd: "2020-11-11 20:00:00",
    logHours: 3,
    reason: "none",
    status: "Chờ duyệt",
    processNote: "",
    respondenceId: 0,
    createAt: "2020-11-11",
    changeStatusTime: "",
    enable: true,
  },
  {
    otLogId: 1,
    staffId: 11,
    otTypeId: 1,
    logStart: "2020-11-11 17:00:00",
    logEnd: "2020-11-11 20:00:00",
    logHours: 3,
    reason: "none",
    status: "Chờ duyệt",
    processNote: "",
    respondenceId: 1,
    createAt: "2020-11-11",
    changeStatusTime: "",
    enable: true,
  },
  {
    otLogId: 1,
    staffId: 11,
    otTypeId: 1,
    logStart: "2020-11-11 17:00:00",
    logEnd: "2020-11-11 20:00:00",
    logHours: 3,
    reason: "none",
    status: "Từ chối",
    processNote: "",
    respondenceId: 2,
    createAt: "2020-11-11",
    changeStatusTime: "2020-11-11",
    enable: true,
  },
  {
    otLogId: 1,
    staffId: 11,
    otTypeId: 1,
    logStart: "2020-11-11 17:00:00",
    logEnd: "2020-11-11 20:00:00",
    logHours: 3,
    reason: "none",
    status: "Đồng ý",
    processNote: "",
    respondenceId: 3,
    createAt: "2020-11-11",
    changeStatusTime: "2020-11-11",
    enable: true,
  },
  {
    otLogId: 1,
    staffId: 11,
    otTypeId: 1,
    logStart: "2020-11-11 17:00:00",
    logEnd: "2020-11-11 20:00:00",
    logHours: 3,
    reason: "none",
    status: "Đồng ý",
    processNote: "",
    respondenceId: 4,
    createAt: "2020-11-11",
    changeStatusTime: "2020-11-11",
    enable: true,
  },
  {
    otLogId: 1,
    staffId: 11,
    otTypeId: 1,
    logStart: "2020-11-11 17:00:00",
    logEnd: "2020-11-11 20:00:00",
    logHours: 3,
    reason: "none",
    status: "Chờ duyệt",
    processNote: "",
    respondenceId: 5,
    createAt: "2020-11-11",
    changeStatusTime: "2020-11-11",
    enable: true,
  },
];

export const CONTRACTTYPE = [
  { contractTypeId: 1, name: "Hợp đồng không xác định hạn", description: "" },
  { contractTypeId: 2, name: "Hợp đồng xác định hạn", description: "" },
];

export const CONTRACT = {
  contractId: 4,
  staffId: 4,
  startDate: "2020-01-01",
  endDate: "",
  taxableSalary: 20000000,
  salary: 20000000,
  workDatePerWeek: 5,
  note: "",
  noOfDependences: 1,
  contractTypeId: 1,
  salaryType: "GrossToNet",
  paidDateNote: "ngày 25 hàng tháng",
  contractFile: "",
  createAt: "",
  changeAt: "",
  contractStatus: 1,
};

export const CONTRACTLIST = [
  {
    contractId: 1,
    staffId: 1,
    startDate: "2020-01-01",
    endDate: "",
    taxableSalary: 20000000,
    salary: 20000000,
    workDatePerWeek: 5,
    note: "",
    noOfDependences: 1,
    contractTypeId: 1,
    salaryType: "GrossToNet",
    paidDateNote: "ngày 25 hàng tháng",
    contractFile: "",
    createAt: "",
    changeAt: "",
    contractStatus: 1,
  },
  {
    contractId: 2,
    staffId: 2,
    startDate: "2020-01-01",
    endDate: "",
    taxableSalary: 20000000,
    salary: 20000000,
    workDatePerWeek: 5,
    note: "",
    noOfDependences: 1,
    contractTypeId: 1,
    salaryType: "GrossToNet",
    paidDateNote: "ngày 25 hàng tháng",
    contractFile: "",
    createAt: "",
    changeAt: "",
    contractStatus: 1,
  },
  {
    contractId: 3,
    staffId: 3,
    startDate: "2020-01-01",
    endDate: "",
    taxableSalary: 20000000,
    salary: 20000000,
    workDatePerWeek: 5,
    note: "",
    noOfDependences: 1,
    contractTypeId: 1,
    salaryType: "GrossToNet",
    paidDateNote: "ngày 25 hàng tháng",
    contractFile: "",
    createAt: "",
    changeAt: "",
    contractStatus: 1,
  },
  {
    contractId: 4,
    staffId: 4,
    startDate: "2020-01-01",
    endDate: "",
    taxableSalary: 20000000,
    salary: 20000000,
    workDatePerWeek: 5,
    note: "",
    noOfDependences: 1,
    contractTypeId: 1,
    salaryType: "GrossToNet",
    paidDateNote: "ngày 25 hàng tháng",
    contractFile: "",
    createAt: "",
    changeAt: "",
    contractStatus: 1,
  },
];

export const ALLOWANCETYPE = [
  {
    allowanceTypeId: 1,
    allowanceName: "Phụ cấp trách nhiệm",
    allowanceDetailSalary: "Không quá 10%",
  },
  {
    allowanceTypeId: 2,
    allowanceName: "Phụ cấp thu hút",
    allowanceDetailSalary: "Dưới 35%",
  },
  {
    allowanceTypeId: 3,
    allowanceName: "Phụ cấp lưu động",
    allowanceDetailSalary: "Dưới 10%",
  },
  {
    allowanceTypeId: 4,
    allowanceName: "Phụ cấp chức vụ",
    allowanceDetailSalary: "Dưới 15%",
  },
  {
    allowanceTypeId: 5,
    allowanceName: "Phụ cấp gửi xe và ăn trưa",
    allowanceDetailSalary: "Tùy thỏa thuận",
  },
];

export const ALLOWANCE = [
  {
    allowanceId: 1,
    contractId: 1,
    allowanceTypeId: 1,
    allowanceSalary: 2000000,
  },
  {
    allowanceId: 2,
    contractId: 1,
    allowanceTypeId: 2,
    allowanceSalary: 2000000,
  },
  {
    allowanceId: 3,
    contractId: 2,
    allowanceTypeId: 5,
    allowanceSalary: 2000000,
  },
  {
    allowanceId: 4,
    contractId: 3,
    allowanceTypeId: 5,
    allowanceSalary: 2000000,
  },
  {
    allowanceId: 5,
    contractId: 4,
    allowanceTypeId: 5,
    allowanceSalary: 2000000,
  },
  {
    allowanceId: 6,
    contractId: 1,
    allowanceTypeId: 5,
    allowanceSalary: 2000000,
  },
];

export const LEAVETYPE = [
  {
    leaveTypeId: 1,
    leaveTypeName: "Nghỉ phép có lương",
    leaveTypeDetail: "",
    leaveTypeDay: 12,
    isSalary: 1,
  },
  {
    leaveTypeId: 2,
    leaveTypeName: "Nghỉ phép không lương",
    leaveTypeDetail: "",
    leaveTypeDay: 20,
    isSalary: 0,
  },
  {
    leaveTypeId: 3,
    leaveTypeName: "Nghỉ phép sự kiện",
    leaveTypeDetail: "",
    leaveTypeDay: 7,
    isSalary: 1,
  },
];

export const LEAVELOG = [
  {
  leaveLogId: 1,
  staffId: 1,
  leaveTypeId: 1,
  leaveStart: "2023-11-11",
  leaveEnd: "2023-11-12",
  leaveDays: 1,
  leaveHours: 8,
  description: "",
  status: "Chờ duyệt",
  createAt: "2023-11-10",
  processNote: "",
  respondencesId: 0,
  changeStatusTime: "",
  enable: 1,
},
];

export const TICKETYPES = [
  { ticketTypeId: 1, ticketName: "Đơn xin nghỉ việc" },
  { ticketTypeId: 2, ticketName: "Yêu cầu cập nhật thông tin cá nhân" },
  { ticketTypeId: 3, ticketName: "Yêu cầu cập nhật hợp đồng" },
  { ticketTypeId: 4, ticketName: "Đơn đề cử ứng viên" },
  { ticketTypeId: 5, ticketName: "Các loại đơn khác" },
];

export const TICKET = {
  ticketId: 1,
  staffId: 1,
  ticketTypeId: 1,
  ticketReason: "none",
  ticketFile: "none",
  ticketStatus: "Chấp nhận",
  createAt: "2023-01-01",
  processNote: "",
  respondencesId: 4,
  changeStatusTime: "",
  enable: true,
};

export const FORMSTATUS = {
  pending: "pending",
  agree: "Chấp nhận",
  disagree: "Từ chối",
};
